# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('4', 'Visa'), ('5', 'Master')], max_length=6)),
                ('number', models.CharField(max_length=20)),
                ('dtExpiry', models.DateField()),
                ('addBill', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sortOrder', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kred.CategoryMerchant')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMerchant', models.CharField(max_length=200)),
                ('npwp', models.CharField(blank=True, max_length=20)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kred.CategoryMerchant')),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrMail', models.CharField(blank=True, max_length=10, null=True)),
                ('imgVrf3', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TxnKey', models.CharField(max_length=15)),
                ('dateTxn', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('flow', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('catTxn', models.CharField(max_length=200)),
                ('invoiceImg', models.ImageField(upload_to=b'')),
                ('tmpMchntName', models.CharField(max_length=200)),
                ('tmpMchntPhon', models.CharField(max_length=50)),
                ('tmpMchntAcctNo', models.CharField(max_length=50)),
                ('tmpMchntAcctNm', models.CharField(max_length=200)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kred.Card')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kred.Merchant')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFull', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kred.Payee'),
        ),
    ]
