# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payer',
            name='addrMail',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
