# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kred', '0003_card_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMerchant', models.CharField(max_length=200)),
                ('npwp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TxnKey', models.CharField(max_length=15)),
                ('dateTxn', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('catTxn', models.CharField(max_length=200)),
                ('invoiceImg', models.ImageField(upload_to=b'')),
                ('tmpMchntName', models.CharField(max_length=200)),
                ('tmpMchntPhon', models.CharField(max_length=50)),
                ('tmpMchntAcctNo', models.CharField(max_length=50)),
                ('tmpMchntAcctNm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFull', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kred.Payee'),
        ),
    ]
