# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kred', '0004_auto_20170813_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgBanner', models.ImageField(upload_to='images/promo/')),
                ('dateFr', models.DateField()),
                ('dateTo', models.DateField()),
            ],
        ),
    ]
