# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kred', '0005_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
