# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kred', '0010_txn_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='addBill',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='dtExpiry',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('4', 'Visa'), ('5', 'Master')], default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='txn',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
