# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFull', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='media/images/users/')),
                ('livingAddress', models.CharField(blank=True, max_length=10, null=True)),
                ('verificationImage1', models.ImageField(blank=True, upload_to='images/')),
                ('verificationImage2', models.ImageField(blank=True, upload_to='images/')),
                ('verificationImage3', models.ImageField(blank=True, upload_to='images/')),
                ('verificationImage4', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
