# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/images/users/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nameFull',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verificationImage1',
            field=models.ImageField(blank=True, upload_to='media/images/users/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verificationImage2',
            field=models.ImageField(blank=True, upload_to='media/images/users/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verificationImage3',
            field=models.ImageField(blank=True, upload_to='media/images/users/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verificationImage4',
            field=models.ImageField(blank=True, upload_to='media/images/users/'),
        ),
    ]
