# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_auto_20170817_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
