# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0004_merchant_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('flow', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=200)),
                ('invoice', models.ImageField(upload_to=b'')),
                ('tmpMchntName', models.CharField(max_length=200)),
                ('tmpMchntPhon', models.CharField(max_length=50)),
                ('tmpMchntAcctNo', models.CharField(max_length=50)),
                ('tmpMchntAcctNm', models.CharField(max_length=200)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchants.Merchant')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
